app:
  lock_file: ./instance/app.lock
  jwt_key: ff08fca37e192d092fce59a2dc1ec9ce638db7fc4b972fc4
  jwt_expiry_mins: 1440
  data_files:
    users_data_file: ./instance/users.json
    user_tokens_data_file: ./instance/user_tokens.json
    user_security_roles_data_file: ./instance/user_security_roles.json
    points_data_file: ./instance/points.json
