GET https://localhost:8888/api/points
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjEzODQ5MDAsImV4cCI6MTcyMTM4NDkxNX0.EjaXcpmuaOwiF-wb91aLhJmxenRfT_XpAM-zmdUDiFk

###

POST https://localhost:8888/api/points
Content-Type: application/json

{
  "id": "1",
  "name": "fred"
}

###

POST https://localhost:8888/login
Content-Type: application/json

{
  "username": "bob"
}

###

POST https://localhost:8888/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyZWQiLCJwYXNzd29yZCI6IiQyYiQxMCRKQmFTSHBBckJ0dFhXN3pvdFRLT3hlZDRkVHdKclJlYUs3UXJqcVJkMk1JS1REbkRjQ29kdSIsImlhdCI6MTcyMTM4NDg2OX0.HzghhqPT-E8O_SqUwqPsvjGeHn0tJwihdadl7N8vuWw"
}

###

DELETE  https://localhost:8888/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9iIiwiaWF0IjoxNzIxMzgxODAzfQ.Dr-OEqso2Zgc8B5xbkQm5bkmivcnKHB-HUZrkqEaXWU"
}

### 

POST https://localhost:8888/users
Content-Type: application/json

{
  "username": "fred",
  "password": "da-password123"
}

###
POST https://localhost:8888/users/login
Content-Type: application/json

{
  "username": "fred",
  "password": "da-password123"
}
