GET https://localhost:8888/api/points
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyZWQiLCJwYXNzd29yZCI6IiQyYiQxMCRzWFdMTUhpTC53dktOLm5sL0RTU1FlMENSeEJla1ZqSjlEQmd6aWZvRld0YnNrQW5UT1ZqdSIsImlhdCI6MTcyMTM4Njc5NiwiZXhwIjoxNzIxMzg3MDk2fQ.CWLIE8fP5nbIOi6knJwViCxhWQJVBc2wSaFTnoik9vo

###

POST https://localhost:8888/api/points
Content-Type: application/json

{
  "id": "1",
  "name": "fred"
}

###

POST https://localhost:8888/login
Content-Type: application/json

{
  "username": "bob"
}

###

POST https://localhost:8888/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyZWQiLCJwYXNzd29yZCI6IiQyYiQxMCRzb0MvbXdWWkxsalVhWU0yZkx6STUuTVZ2WWhuL3I1cjNQU2tiZElJN01uWTMyVm9YenpJaSIsImlhdCI6MTcyMTM4NjMzNn0.O5m2O78QedPF0CQIi09vq_zAbEgFTAspmlMBhWbtQz8"
}

###

DELETE  https://localhost:8888/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9iIiwiaWF0IjoxNzIxMzgxODAzfQ.Dr-OEqso2Zgc8B5xbkQm5bkmivcnKHB-HUZrkqEaXWU"
}

### 

POST https://localhost:8888/users
Content-Type: application/json

{
  "username": "fred",
  "password": "da-password123"
}

###
POST https://localhost:8888/users/login
Content-Type: application/json

{
  "username": "fred",
  "password": "da-password123"
}
