POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

###

POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

###

GET http://127.0.0.1:5000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTc3NDY1MywianRpIjoiMDYwZTIyMjAtM2M0OC00YWQ5LTkxNzEtNWZhN2NiNzAzNTJjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QiLCJuYmYiOjE3MjE3NzQ2NTMsImNzcmYiOiI2ZmM0ZmRjOC00OGIyLTRiYjUtYTkyNy01Y2FmNmY3NGNiYWUiLCJleHAiOjE3MjE3NzUyNTN9.WfBlGmBxX88sxGOMIHQvX4Vd8XFaLPSyvSR-RDrocqk

###

GET http://127.0.0.1:5000/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTgyNjIyOSwianRpIjoiMDliMDM0MmUtNzE0NS00ZWViLWJjMjMtNDIzN2EyNzhjOWFmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QiLCJuYmYiOjE3MjE4MjYyMjksImNzcmYiOiJmMzhmYjE4Yy04NGUzLTRkMGQtOTVkMy1hYzViZmQyNGFmNWUiLCJleHAiOjE3MjE4MjY4Mjl9.S1BLP8z-lF_meqk4vB3LrS3KPdREMJbycQ-b99SKVDI

###

GET http://127.0.0.1:5000/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTc3NDcwNSwianRpIjoiMTFjMzQxMzYtNDllMS00MjRjLWEzZWQtNTgxZWNiZDk1M2I5IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJ0ZXN0IiwibmJmIjoxNzIxNzc0NzA1LCJjc3JmIjoiYWEwMDZjMmItZmRiYi00MTRjLTg3NzktNmQ2OTMwNzdjZjk0IiwiZXhwIjoxNzI0MzY2NzA1fQ.Ie3pwyq8e7zQResfM5VGtuMh26TocdOD0Fi1SOrJghA

###

GET http://127.0.0.1:5000/auth/who-am-i
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTc3NDY1MywianRpIjoiMDYwZTIyMjAtM2M0OC00YWQ5LTkxNzEtNWZhN2NiNzAzNTJjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QiLCJuYmYiOjE3MjE3NzQ2NTMsImNzcmYiOiI2ZmM0ZmRjOC00OGIyLTRiYjUtYTkyNy01Y2FmNmY3NGNiYWUiLCJleHAiOjE3MjE3NzUyNTN9.WfBlGmBxX88sxGOMIHQvX4Vd8XFaLPSyvSR-RDrocqk
