POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "userName": "test",
  "password": "password"
}

###

POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "userName": "test",
  "password": "password"
}

###

POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin"
}

###

GET http://127.0.0.1:5000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTkwMjc1MCwianRpIjoiMjNkMzVlZGMtZmI0Ni00YzM0LTk1ZTEtYTg4OGE3NjRhNjkyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFkbWluIiwibmJmIjoxNzIxOTAyNzUwLCJjc3JmIjoiZWRhM2NjMjYtYzM4YS00NGMyLWFhZWYtZTM0ZDFlYTEyN2Y0IiwiZXhwIjoxNzIxOTAzMzUwfQ.JtqkkgJJrE2vIDxNORJiUEONRM7TwR0wcuwG7NRb-MU

###

GET http://127.0.0.1:5000/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTkwMjQ0MCwianRpIjoiOWFmZDExZGItNTVkZi00MDk0LWFlMDEtZDQzYjVmNWFhYWRmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QiLCJuYmYiOjE3MjE5MDI0NDAsImNzcmYiOiJlY2E2YzE4NS00ZDkyLTRjNzctODM5Mi1iMTM2MWE5OWZjNWMiLCJleHAiOjE3MjE5MDMwNDB9.PTJdErVPjFg8O7RREPougaey9wVyArJoHZpv8iAbX4w

###

GET http://127.0.0.1:5000/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTkwMjQ4NiwianRpIjoiZGQ3ZWEyNjgtYjM5NS00MzE4LTllZmUtMjIxNjM4ZjNhMDMwIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJhZG1pbiIsIm5iZiI6MTcyMTkwMjQ4NiwiY3NyZiI6ImMzMGUwODJlLTQ5ZDUtNDViYy1iOGM2LTlkNzg4OTNlZTMzNCIsImV4cCI6MTcyNDQ5NDQ4Nn0.RMdmWMJ_o0nmZN21imTEzZ1kJP7eFWFKrF2BM-F9N_I

###

GET http://127.0.0.1:5000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTkwMjQ0MCwianRpIjoiOWFmZDExZGItNTVkZi00MDk0LWFlMDEtZDQzYjVmNWFhYWRmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QiLCJuYmYiOjE3MjE5MDI0NDAsImNzcmYiOiJlY2E2YzE4NS00ZDkyLTRjNzctODM5Mi1iMTM2MWE5OWZjNWMiLCJleHAiOjE3MjE5MDMwNDB9.PTJdErVPjFg8O7RREPougaey9wVyArJoHZpv8iAbX4w
